apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: crater-app
resources:
  # - check-estimates-status.cronjob.yaml
  # - check-invoice-status.cronjob.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - ./files/php-fpm.conf
images:
  - name: invoiceshelf/invoiceshelf
    newTag: 1.0.0@sha256:0438c22ff371bbc6b910e9d4b6288f00036e1fe3313ce9224c0942ab5e57dbb0
